import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import React, { useState } from "react";
import { HiOutlineHome, HiHome } from "react-icons/hi";
import { CiSearch, CiUser } from "react-icons/ci";
import { VscDiffAdded } from "react-icons/vsc";
import { RiMessengerLine, RiNotification2Line } from "react-icons/ri";
import Image from "next/image";
import "tw-elements/dist/css/tw-elements.min.css";
import { AuthProvider } from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Instagram",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="drawer lg:drawer-open">
          <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content flex flex-col m-4">
            {/* Page content here */}
            <AuthProvider>{children}</AuthProvider>
          </div>
          <div className="drawer-side">
            <ul className="menu p-4 w-80 min-h-full bg-base-200 text-base-content ">
              <div className="text-center mb-4 ml-4">
                <Image
                  src="/instagramLine.png"
                  alt="Your Image"
                  width={150}
                  height={150}
                />
              </div>
              {/* Sidebar content here */}
              <li className="my-2">
                <div className="flex ">
                  <HiOutlineHome size={20} />
                  <Link href="/">Home</Link>
                </div>
              </li>
              <li>
                <div className="flex my-2">
                  <CiSearch size={20} />
                  <Link href="/search">Search</Link>
                </div>
              </li>
              <li>
                <div className="flex my-2">
                  <VscDiffAdded size={20} />
                  <Link href="/create">Create</Link>
                  {/* <label onClick={CreateModal />}>Create</label> */}
                </div>
              </li>
              <li>
                <div className="flex my-2">
                  <RiMessengerLine size={20} />
                  <Link href="/message">Message</Link>
                </div>
              </li>
              <li>
                <div className="flex my-2">
                  <RiNotification2Line size={20} />
                  <Link href="/notification">Notification</Link>
                </div>
              </li>
              <li>
                <div className="flex my-2">
                  <CiUser size={20} />
                  <Link href="/profile">Profile</Link>{" "}
                </div>
              </li>
            </ul>
          </div>
        </div>
      </body>
    </html>
  );
}
